Algoritmo "semnome"
// Disciplina :  Lógica de Programação
// Instrutor(a) : Thalia Souza 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/03/2025
Var
num, resto: real

Inicio
Escreval("Informe um número: ")
leia(num)

resto <- num % 2
Escreval("O resto da divisão por 2 é: ", resto)
Escreval("Se o resto for 0, o número é PAR. Se o resto for 1, o número é ÍMPAR!")

Fimalgoritmo