Algoritmo "semnome"
// Disciplina :  Lógica de Programação
// Instrutor(a) : Thalia Souza 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/03/2025
Var
celsius, fahrenheit: real

Inicio

escreval("Informe a temperatura em Celsius: ")
leia(celsius)

fahrenheit <- (celsius * (9/5)) + 32

escreval("A temperatura convertida para Fahrenheit é: " ,fahrenheit)

Fimalgoritmo